DEBUG = False
ENV = 'development'

DATABASE_HOST = ''
DATABASE_USER = ''
DATABASE_PORT = ''
DATABASE_NAME = ''
DATABASE_PWD = ''

SLACK_URL_SERVICE = ''
SLACK_TOKEN = ''

SQLALCHEMY_DATABASE_URI = f'postgresql://{DATABASE_USER}:{DATABASE_PWD}@{DATABASE_HOST}:{DATABASE_PORT}/{DATABASE_NAME}'
SQLALCHEMY_TRACK_MODIFICATIONS = False
