version: "3.7"

networks:
  pocauth:
    name: pocauth
    driver: bridge
    external: true

volumes:
  keycloak-data:

services:
  keycloak-database:
    container_name: keycloak-database
    image: postgres:9.6
    volumes:
      - keycloak-data:/var/lib/postgresql/data
    networks:
      - pocauth
    ports:
      - "25432:5432"
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password

  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:17.0.0
    depends_on:
      - keycloak-database
    command: start-dev
    networks:
      - pocauth
    ports:
      - "8180:8080"
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: keycloak-database
      DB_PORT: 5432
      DB_DATABASE: keycloak
      DB_USER: keycloak
      DB_PASSWORD: password
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    restart: on-failure
  
  authapi:
    container_name: authapi
    build: ./auth-api
    image: authapi
    depends_on:
      - keycloak
    command: uvicorn main:app --reload --workers 1 --host 0.0.0.0 --port 1000
    ports:
      - "1000:1000"
    networks:
      - pocauth
  