version: '3'

volumes:
  prometheus_data: {}
  grafana_data: {}

networks:
  pocauth:
    external: true

services:

  prometheus:
    container_name: prometheus
    hostname: prometheus
    image: prom/prometheus
    networks:
      - pocauth
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - 9090:9090

  grafana:
    container_name: grafana
    hostname: grafana
    image: grafana/grafana
    networks:
      - pocauth
    volumes:
      - ./grafana_datasources.yml:/etc/grafana/provisioning/datasources/all.yaml
      - ./grafana_config.ini:/etc/grafana/config.ini
      - grafana_data:/var/lib/grafana
    ports:
      - 3030:3000