version: "3.7"

networks:
  pocauth:
    name: pocauth
    driver: bridge
    external: true

services:
  servicea:
    container_name: servicea
    build: ./python/serviceA
    image: servicea
    command: uvicorn main:app --reload --workers 1 --host 0.0.0.0 --port 5000
    ports:
      - "5000:5000"
    networks:
      - pocauth

  serviceb:
    container_name: serviceb
    build: ./python/ServiceB
    image: serviceb
    entrypoint: [ "python", "startup.py" ]
    ports:
      - "7000:7000"
    networks:
      - pocauth
