version: "3.8"

networks:
  pocauth:
    external: true

services:
  vaultserver:
    container_name: vaultserver
    image: vault:latest
    cap_add:
      - IPC_LOCK
    ports:
      - "8200:8200"
    environment:
      VAULT_ADDR: $VAULT_ADDR
      VAULT_DEV_ROOT_TOKEN_ID: $VAULT_DEV_TOKEN
    networks:
      - pocauth
