version: "3.7"

networks:
  pocauth:
    name: pocauth
    driver: bridge
    external: true

services:
  servicea:
    container_name: servicea
    build: .
    image: servicea
    command: uvicorn main:app --reload --workers 1 --host 0.0.0.0 --port 5000
    ports:
      - "5000:5000"
    networks:
      - pocauth
