version: "3.7"

networks:
  pocauth:
    name: pocauth
    driver: bridge
    external: true

services:
  servicea:
    container_name: servicea
    build: .
    image: servicea
    entrypoint: [ "sh", "-c", "chmod +x ./startup.sh && source ./startup.sh"]
    ports:
      - "5000:5000"
    networks:
      - pocauth
