version: '3.4'

networks:
  pocauth:
    external: true

volumes:
  kong-data: 

services:
  kong-migrations:
    container_name: kong-migration
    image: kong
    command: kong migrations bootstrap
    depends_on:
      - kong-database
    environment:
      KONG_DATABASE: $KONG_DB
      KONG_PG_DATABASE: $KONG_PG_DB
      KONG_PG_HOST: $KONG_PG_HOST
      KONG_PG_USER: $KONG_PG_USER
      KONG_PG_PASSWORD: $KONG_PG_PWD
    restart: on-failure
    networks:
      - pocauth

  kong-migrations-up:
    image: kong
    container_name: kong-migrations-up
    command: kong migrations up && kong migrations finish
    depends_on:
      - kong-database
    environment:
      KONG_DATABASE: $KONG_DB
      KONG_PG_DATABASE: $KONG_PG_DB
      KONG_PG_HOST: $KONG_PG_HOST
      KONG_PG_USER: $KONG_PG_USER
      KONG_PG_PASSWORD: $KONG_PG_PWD
    restart: on-failure
    networks:
      - pocauth

  kong:
    build: .
    container_name: kong
    restart: on-failure
    depends_on:
      - kong-database
    environment:
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ERROR_LOG: /dev/stderr
      KONG_ADMIN_LISTEN: '0.0.0.0:8001'
      KONG_CASSANDRA_CONTACT_POINTS: $KONG_PG_HOST
      KONG_DATABASE: $KONG_DB
      KONG_PG_DATABASE: $KONG_PG_DB
      KONG_PG_HOST: $KONG_PG_HOST
      KONG_PG_USER: $KONG_PG_USER
      KONG_PG_PASSWORD: $KONG_PG_PWD
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_PLUGINS: bundled,oidc,jwt-keycloak
    networks:
      - pocauth
    ports:
      - "8000:8000/tcp"
      - "127.0.0.1:8001:8001/tcp"
      - "8443:8443/tcp"
      - "127.0.0.1:8444:8444/tcp"

  kong-database:
    container_name: kong-database
    image: postgres:9.6
    restart: on-failure
    environment:
      POSTGRES_DB: $KONG_PG_DB
      POSTGRES_USER: $KONG_PG_USER
      POSTGRES_PASSWORD: $KONG_PG_PWD
    stdin_open: true
    tty: true
    networks:
      - pocauth

  konga-prepare:
    container_name: konga-prepare
    image: pantsel/konga:latest
    command: "-c prepare -a postgres -u ${KONGA_DB_URI}"
    restart: on-failure
    networks:
      - pocauth
    depends_on:
      - kong-database

  konga:
    container_name: konga
    image: pantsel/konga:latest
    restart: always
    networks:
      - pocauth
    environment:
      DB_ADAPTER: $DB_ADAPTER
      DB_HOST: $KONG_PG_HOST
      DB_USER: $KONG_PG_USER
      DB_PASSWORD: $KONG_PG_PWD
      DB_DATABASE: $KONGA_DB
      NODE_ENV: production
    depends_on:
      - kong-database
    ports:
      - "1337:1337"